# Search engine
<hr>

# Install packages

In [0]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /local_disk0/.ephemeral_nfs/envs/pythonEnv-71ef0264-7cfc-4c71-a4bd-323e2d0bab82/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /local_disk0/.ephemeral_nfs/envs/pythonEnv-71ef0264-7cfc-4c71-a4bd-323e2d0bab82/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
!pip install googletrans

Requirement already satisfied: googletrans in /local_disk0/.ephemeral_nfs/envs/pythonEnv-71ef0264-7cfc-4c71-a4bd-323e2d0bab82/lib/python3.12/site-packages (4.0.2)
Requirement already satisfied: httpx>=0.27.2 in /databricks/python3/lib/python3.12/site-packages (from httpx[http2]>=0.27.2->googletrans) (0.28.1)
Requirement already satisfied: anyio in /databricks/python3/lib/python3.12/site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans) (4.7.0)
Requirement already satisfied: certifi in /databricks/python3/lib/python3.12/site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /databricks/python3/lib/python3.12/site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans) (1.0.9)
Requirement already satisfied: idna in /databricks/python3/lib/python3.12/site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans) (3.7)
Requirement already satisfied: h11>=0.16 in /databricks/python3/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans) (0.16.0)
Requirement already satisfied: h2<5,>=3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-71ef0264-7cfc-4c71-a4bd-323e2d0bab82/lib/python3.12/site-packages (from httpx[http2]>=0.27.2->googletrans) (4.3.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-71ef0264-7cfc-4c71-a4bd-323e2d0bab82/lib/python3.12/site-packages (from h2<5,>=3->httpx[http2]>=0.27.2->googletrans) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-71ef0264-7cfc-4c71-a4bd-323e2d0bab82/lib/python3.12/site-packages (from h2<5,>=3->httpx[http2]>=0.27.2->googletrans) (4.1.0)
Requirement already satisfied: sniffio>=1.1 in /databricks/python3/lib/python3.12/site-packages (from anyio->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans) (1.3.0)
Requirement already satisfied: typing_extensions>=4.5 in /databricks/python3/lib/python3.12/site-packages (from anyio->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans) (4.12.2)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
!pip install nltk

Requirement already satisfied: nltk in /local_disk0/.ephemeral_nfs/envs/pythonEnv-71ef0264-7cfc-4c71-a4bd-323e2d0bab82/lib/python3.12/site-packages (3.9.4)
Requirement already satisfied: click in /databricks/python3/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /databricks/python3/lib/python3.12/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /databricks/python3/lib/python3.12/site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /databricks/python3/lib/python3.12/site-packages (from nltk) (4.67.1)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

# Import packages

In [0]:
# basic packages

import pandas as pd
import numpy as np
import re

# transalte

from googletrans import Translator

# NLP 

import nltk
from nltk.corpus import stopwords
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [0]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/spark-71ef0264-7cfc-4c71-a4bd-32/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

# Retrieval data

In [0]:
df_zeus = pd.read_excel('./data/Repositorio Zeus II.xlsx')

In [0]:
# show data

df_zeus.head()

   N                         Autor 1  ... Diapositivas Simulacion
0  1       DANNY MARIO OROPEZA ROJAS  ...          NaN   No tiene
1  2   ESPINOZA HINOJOSA JOSE ISRAEL  ...     No tiene   No tiene
2  3  CHIRINOS LOZADA JAVIER SERAPIO  ...     No tiene   No tiene
3  4        CARLA VIVIAN ROJAS NAVIA  ...     No tiene   No tiene
4  5    VASQUEZ FLORES YOSHIDA IVETT  ...     No tiene   No tiene

[5 rows x 17 columns]

In [0]:
df_zeus.shape

(1172, 17)

# Search engine - titles

In [0]:
df_all_trans = pd.read_excel('./data/summarize_tesis.xlsx')

In [0]:
df_all_trans.head()

   N  ...                                   summarize_thesis
0  1  ...  The main objective of the degree project is to...
1  2  ...  Camu camu is a variety of fruit that has its o...
2  3  ...  The desired objectives were met in the eight c...
3  4  ...  The telecommunications company VIVA-GSM has a ...
4  5  ...  The main objective of this project was to carr...

[5 rows x 19 columns]

In [0]:
def limpiar_texto(t):
    t = t.lower()
    t = re.sub(r"[^\w\s]", "", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t

In [0]:
# select thesis titles

list_titles = df_all_trans['thesis_title'].values.tolist()
list_titles_es = df_all_trans['Titulo'].values.tolist()

In [0]:
# clear data

stop_words = set(stopwords.words("english"))

list_titles_stop = [" ".join([word.lower() for word in titulo.split() if word.lower() not in stop_words])
                          for titulo in list_titles]
                          
list_titles_stop = [limpiar_texto(x) for x in list_titles_stop]

In [0]:
# view 5 thesis names

list_titles_stop[0:5]

['feasibility project implementation biodiesel processing plant industrias admsao sa',
 'economic financial feasibility project installation camu camu processing plant',
 'feasibility study paper recycling plant within umss',
 'diagnosis internal collection system financial services unit vivagsm company',
 'feasibility study implementation plant produce sweet cassava starch export']

## max_features = None, ngram_range=(1, 2)

In [0]:
# create model by default, (2) n-grams

vectorizer = TfidfVectorizer(ngram_range=(1, 2)) #  max_features=50
X = vectorizer.fit_transform(list_titles_stop)

In [0]:
# create tf-idf matrix

df_tf_idf_titles = pd.DataFrame(columns =  vectorizer.get_feature_names_out(), data = X.toarray(), index = list_titles_stop)

In [0]:
# matrix dimension

df_tf_idf_titles.shape

(1172, 8806)

In [0]:
# RAM usage

df_tf_idf_titles.info() # 78.7+ MB

<class 'pandas.core.frame.DataFrame'>
Index: 1172 entries, feasibility project implementation biodiesel processing plant industrias admsao sa to feasibility study production marketing fruit coffee chañar metropolitan axis cochabamba
Columns: 8806 entries, 000 to álvarez company
dtypes: float64(8806)
memory usage: 78.7+ MB

In [0]:
df_tf_idf_titles.head(2)

                                                    000  ...  álvarez company
feasibility project implementation biodiesel pr...  0.0  ...              0.0
economic financial feasibility project installa...  0.0  ...              0.0

[2 rows x 8806 columns]

Similitud por cosenos

![image_1777070277026.png](./image_1777070277026.png "image_1777070277026.png")

In [0]:
def search_similar_documents(query,vectorizer,X,list_titles_en, list_titles_es, k = 5):

    query_vec = vectorizer.transform([query])

    similarities = cosine_similarity(query_vec, X)[0]

    top_indices = np.argsort(similarities)[::-1][:k]

    for i in top_indices:
        print(f"Score: {similarities[i]:.4f}")
        print(f"Documento (EN): {list_titles_en[i]}")
        print(f"Documento (ES): {list_titles_es[i]}")
        print("-" * 50, end = '\n\n')

    return top_indices

In [0]:
# search test 1 

query = 'academic plan'

search_similar_documents(query,vectorizer,X,list_titles, list_titles_es)

Score: 0.3097
Documento (EN): ACADEMIC DEVELOPMENT PLAN FOR THE ELECTROMECHANICAL ENGINEERING CAREER 2019 – 2023
Documento (ES): PLAN DE DESARROLLO ACADÉMICO DE LA CARRERA DE INGENIERÍA ELECTROMECÁNICA 2019 – 2023
--------------------------------------------------

Score: 0.0739
Documento (EN): DESIGN OF AN OCCUPATIONAL SAFETY AND HYGIENE PLAN
Documento (ES): DISEÑO DE UN PLAN DE SEGURIDAD E HIGIENE OCUPACIONAL
--------------------------------------------------

Score: 0.0572
Documento (EN): DESIGN OF A FOOD SAFETY PLAN BASED ON HACCP AND AN INDUSTRIAL SAFETY AND OCCUPATIONAL HYGIENE PLAN FOR THE COMPANY INDUSTRIAS DEL MOLLE S.R.L.
Documento (ES): DISEÑO DE UN PLAN DE INOCUIDAD ALIMENTARIA BASADA EN EL HACCP Y UN PLAN DE SEGURIDAD INDUSTRIAL E HIGIENE OCUPACIONAL PARA LA EMPRESA INDUSTRIAS DEL MOLLE S.R.L
--------------------------------------------------

Score: 0.0547
Documento (EN): STRATEGIC MARKETING PLAN FOR THE VANGUARD COMPANY
Documento (ES): PLAN ESTRATÉGICO DE MARKETING PARA LA EMPRESA VANGUARDIA
--------------------------------------------------

Score: 0.0542
Documento (EN): INDUSTRIAL SAFETY PLAN FOR THE ILUMINA COMPANY.
Documento (ES): PLAN DE SEGURIDAD INDUSTRIAL PARA LA EMPRESA ILUMINA.
--------------------------------------------------

array([1020,  984,  461,  352,  525])

In [0]:
# search test 2 

query = 'ypfb'

search_similar_documents(query,vectorizer,X,list_titles, list_titles_es)

Score: 0.3029
Documento (EN): INDUSTRIAL SAFETY AND HYGIENE PLAN FOR THE COMPANY “YPFB FLAMAGAS S.A.”
Documento (ES): PLAN DE SEGURIDAD E HIGIENE INDUSTRIAL PARA LA EMPRESA  “YPFB FLAMAGAS S.A.
--------------------------------------------------

Score: 0.2797
Documento (EN): STRATEGIC MARKETING PLAN FOR THE NEW LINE OF YPFB INDUSTRIAL LUBRICANTS.
Documento (ES): PLAN ESTRATÉGICO DE MARKETING PARA LA NUEVA LÍNEA DE LUBRICANTES INDUSTRIALES YPFB.
--------------------------------------------------

Score: 0.2385
Documento (EN): EVALUATION AND DEVELOPMENT OF IMPROVEMENTS OF THE OPERATIONAL PROCESSES IN “YPFB LOGÍSTICA-PLANTA COCHABAMBA”
Documento (ES): EVALUACIÓN Y DESARROLLO DE MEJORAS DE LOS PROCESOS OPERACIONALES EN ”YPFB LOGÍSTICA-PLANTA COCHABAMBA”
--------------------------------------------------

Score: 0.2108
Documento (EN): PREFEASIBILITY STUDY FOR A DAP/NPK MINERAL FERTILIZER PRODUCTION PLANT IN BOLIVIA, FOR THE INDUSTRIALIZATION MANAGEMENT OF YPFB
Documento (ES): ESTUDIO DE PREFACTIBILIDAD PARA UNA PLANTA PRODUCTORA DE FERTILIZANTES MINERALES DAP/NPK EN BOLIVIA, PARA LA GERENCIA DE INDUSTRIALIZACIÓN DE YPFB
--------------------------------------------------

Score: 0.2052
Documento (EN): PREPARATION OF A PROCEDURES MANUAL BASED ON THE PROCESS MANAGEMENT MODEL FOR THE YPFB VALLEHERMOSO COCHABAMBA PACKING PLANT
Documento (ES): ELABORACION DE UN MANUAL DE PROCEDIMIENTOS BASADO EN EL MODELO DE GESTION POR PROCESOS PARA LA PLANTA ENGARRAFADORA DE YPFB VALLEHERMOSO COCHABAMBA
--------------------------------------------------

array([ 820, 1084,  373,  267,  450])

## max_features = 50

In [0]:
# create model by default, (2) n-grams

vectorizer_50 = TfidfVectorizer(ngram_range=(1, 2),max_features=50) #  max_features=50
X_50 = vectorizer_50.fit_transform(list_titles_stop)

In [0]:
# create tf-idf matrix

df_tf_idf_titles_50 = pd.DataFrame(columns =  vectorizer_50.get_feature_names_out(), data = X_50.toarray(), index = list_titles_stop)

In [0]:
# vectorizer_50.get_feature_names_out()[0:500]

In [0]:
df_tf_idf_titles_50.head(2)

                                                    based  ...  technical
feasibility project implementation biodiesel pr...    0.0  ...        0.0
economic financial feasibility project installa...    0.0  ...        0.0

[2 rows x 50 columns]

In [0]:
df_tf_idf_titles_50.shape

(1172, 50)

In [0]:
# RAM usage

df_tf_idf_titles_50.info() # 467.0+ KB

<class 'pandas.core.frame.DataFrame'>
Index: 1172 entries, feasibility project implementation biodiesel processing plant industrias admsao sa to feasibility study production marketing fruit coffee chañar metropolitan axis cochabamba
Data columns (total 50 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   based                   1172 non-null   float64
 1   based iso               1172 non-null   float64
 2   city                    1172 non-null   float64
 3   cochabamba              1172 non-null   float64
 4   company                 1172 non-null   float64
 5   control                 1172 non-null   float64
 6   department              1172 non-null   float64
 7   department cochabamba   1172 non-null   float64
 8   design                  1172 non-null   float64
 9   development             1172 non-null   float64
 10  feasibility             1172 non-null   float64
 11  feasibility project     1172 non-null   float64
 12  feasibility study       1172 non-null   float64
 13  health                  1172 non-null   float64
 14  hygiene                 1172 non-null   float64
 15  hygiene plan            1172 non-null   float64
 16  implementation          1172 non-null   float64
 17  industrial              1172 non-null   float64
 18  industrial safety       1172 non-null   float64
 19  installation            1172 non-null   float64
 20  iso                     1172 non-null   float64
 21  line                    1172 non-null   float64
 22  ltda                    1172 non-null   float64
 23  management              1172 non-null   float64
 24  management system       1172 non-null   float64
 25  marketing               1172 non-null   float64
 26  marketing plan          1172 non-null   float64
 27  model                   1172 non-null   float64
 28  occupational            1172 non-null   float64
 29  plan                    1172 non-null   float64
 30  planning                1172 non-null   float64
 31  plant                   1172 non-null   float64
 32  process                 1172 non-null   float64
 33  processing              1172 non-null   float64
 34  processing plant        1172 non-null   float64
 35  production              1172 non-null   float64
 36  project                 1172 non-null   float64
 37  project implementation  1172 non-null   float64
 38  quality                 1172 non-null   float64
 39  quality management      1172 non-null   float64
 40  sa                      1172 non-null   float64
 41  safety                  1172 non-null   float64
 42  srl                     1172 non-null   float64
 43  standard                1172 non-null   float64
 44  strategic               1172 non-null   float64
 45  study                   1172 non-null   float64
 46  study implementation    1172 non-null   float64
 47  system                  1172 non-null   float64
 48  system based            1172 non-null   float64
 49  technical               1172 non-null   float64
dtypes: float64(50)
memory usage: 467.0+ KB

In [0]:
# search test 3 

query = "academic plan"

search_similar_documents(query, vectorizer_50,X_50,list_titles_stop, list_titles_es)

Score: 1.0000
Documento (EN): business plan intensive breeding castilla rabbits province punata
Documento (ES): PLAN DE NEGOCIOS PARA LA CRIANZA INTENSIVA DE CONEJOS DE CASTILLA EN LA PROVINCIA DE PUNATA
--------------------------------------------------

Score: 1.0000
Documento (EN): business plan export wooden interior furniture united states market
Documento (ES): PLAN DE NEGOCIOS PARA LA EXPORTACIÓN DE MUEBLES INTERIORES DE MADERA AL MERCADO DE LOS ESTADOS UNIDOS
--------------------------------------------------

Score: 1.0000
Documento (EN): modernization plan quiroz bakery
Documento (ES): PLAN DE MODERNIZACIÓN DE LA PANADERÍA QUIROZ
--------------------------------------------------

Score: 1.0000
Documento (EN): plan conformation textiles clothing cluster faculty sciences technology umss
Documento (ES): PLAN PARA LA CONFORMACIÓN DE UN CLÚSTER DE TEXTILES Y CONFECCIONES EN LA FACULTAD DE CIENCIAS Y TECNOLOGÍA DE LA UMSS
--------------------------------------------------

Score: 1.0000
Documento (EN): preparation business plan creation private educational unit condebamba sector
Documento (ES): ELABORACIÓN DE UN PLAN DE EMPRESA PARA LA CREACIÓN DE UNA UNIDAD EDUCATIVA PRIVADA EN EL SECTOR CONDEBAMBA
--------------------------------------------------

array([699, 190,  74, 994, 356])

In [0]:
# search test 4

query = "ypfb"

search_similar_documents(query, vectorizer_50,X_50,list_titles_stop, list_titles_es)

Score: 0.0000
Documento (EN): feasibility study production marketing fruit coffee chañar metropolitan axis cochabamba
Documento (ES): ESTUDIO DE FACTIBILIDAD PARA LA PRODUCCIÓN Y COMERCIALIZACIÓN DE CAFÉ DEL FRUTO
                  DE CHAÑAR EN EL EJE METROPOLITANO DE COCHABAMBA
--------------------------------------------------

Score: 0.0000
Documento (EN): industrial safety management plan inquibol company
Documento (ES): PLAN DE GESTIÓN DE SEGURIDAD INDUSTRIAL PARA LA EMPRESA INQUIBOL.
--------------------------------------------------

Score: 0.0000
Documento (EN): identification evaluation occupational risks municipal drinking water sewer service company semapa
Documento (ES): IDENTIFICACIÓN Y EVALUACIÓN DE RIESGOS LABORALES PARA LA EMPRESA DE SERVICIO MUNICIPAL DE AGUA POTABLE Y ALCANTARILLADO SEMAPA.
--------------------------------------------------

Score: 0.0000
Documento (EN): development implementation methodology improve efficiency embol sa plant cochabamba
Documento (ES): DESARROLLO E IMPLEMENTACIÓN DE UNA METODOLOGÍA DE  MEJORA DE EFICIENCIA EN PLANTA DE EMBOL S.A. - COCHABAMBA
--------------------------------------------------

Score: 0.0000
Documento (EN): feasibility project export canned papaya argentine republic
Documento (ES): PROYECTO DE FACTIBILIDAD PARA LA EXPORTACIÓN DE PAPAYA EN CONSERVA A LA REPUBLICA ARGENTINA
--------------------------------------------------

array([1171,  401,  385,  386,  387])

# Search engine - abstract

In [0]:
df_all_trans.head(1)

   N  ...                                   summarize_thesis
0  1  ...  The main objective of the degree project is to...

[1 rows x 19 columns]

In [0]:
df_all_trans.isna().sum()

N                   0
Autor 1             0
Autor 2             0
Tutor               0
Titulo              0
Semestre            0
email               0
Modalidad           1
Codigo              0
Calificacion        0
Categoria           0
Palabras clave      0
Resumen             1
Enlace tesis        0
Enlace Resumen      4
Diapositivas        1
Simulacion          0
thesis_title        0
summarize_thesis    1
dtype: int64

In [0]:
df_all_trans_clear = df_all_trans.dropna()

In [0]:
df_all_trans_clear.isna().sum()

N                   0
Autor 1             0
Autor 2             0
Tutor               0
Titulo              0
Semestre            0
email               0
Modalidad           0
Codigo              0
Calificacion        0
Categoria           0
Palabras clave      0
Resumen             0
Enlace tesis        0
Enlace Resumen      0
Diapositivas        0
Simulacion          0
thesis_title        0
summarize_thesis    0
dtype: int64

In [0]:
# select thesis abstracts

list_abstract = df_all_trans_clear['summarize_thesis'].values.tolist()
list_abstract_es = df_all_trans_clear['Resumen'].values.tolist()

In [0]:
# select thesis title

list_title_clear= df_all_trans_clear['thesis_title'].values.tolist()
list_title_clear_es = df_all_trans_clear['Titulo'].values.tolist()

In [0]:
list_abstract_stop = [" ".join([word.lower() for word in titulo.split() if word.lower() not in stop_words])
                          for titulo in list_abstract]
                          
list_abstract_stop = [limpiar_texto(x) for x in list_abstract_stop]

## max_features = None

In [0]:
# create model by default, (2) n-grams

vectorizer_abs = TfidfVectorizer(ngram_range=(1, 2)) #  max_features=50
X_abs = vectorizer_abs.fit_transform(list_abstract_stop)

In [0]:
# create tf-idf matrix

df_tf_idf_abs = pd.DataFrame(columns = vectorizer_abs.get_feature_names_out(), data = X_abs.toarray(), index = list_abstract_stop)

In [0]:
df_tf_idf_abs.shape

(1165, 151960)

In [0]:

# RAM usage 

df_tf_idf_abs.info() # memory usage: 1.3+ GB

<class 'pandas.core.frame.DataFrame'>
Index: 1165 entries, camu camu variety fruit origin banks rivers peruvian amazon that due peculiar characteristics recent introduction world markets promises promising crop research carried institute nutrition peru national agrarian university la molina unalm demonstrated high content ascorbic acid camucamu pulp importance economic value mainly due high content ascorbic acid vitamin c element used pharmacological industry natural source vitamin c comparatively camucamu 30 60 times ascorbic acid oranges lemons therefore cultivation camu camu cochabamba tropics constitutes efficient alternative planting illicit crops given within alternative development programs market study divided into market research jam fruit tea based surveys directed homes points sale camucamu pulp market research aimed local foreign market tasting test camucamu fruit jam pulp observed factors influenced determination size mainly characteristics consumer market is demand production technology availability financial resources plant macro located city cochabamba three areas considered micro location parque industrial santivañez sacaba entre ríos chapare camu camu species native amazon grows mainly peru introduced brazil many years ago recently colombia venezuela bolivia high content ascorbic acid vitamin c makes camu camu fruit attractive international market vitamin c important antioxidant selected process simple semiartisanal since good part sequence carried manually help utensils simple industrial equipment stages production process divided three modules one product project is jam pulp tea stages consist of reception selection washing prepared fruit papaya camu camu pulped refined homogenization part camu camu pulp destined classification packaging frozen pulp part camu papaya pulp goes concentrate stage production jam tea made rejected husks comes packaging storage jam pulp tea organic structure determined based projects investment plans administrative technology complexity operations labor needs determined based technical administrative demands project range senior personnel unskilled labor organization company basically identifies three departments production administration marketing addition general management totaling contraction 17 people 9 direct labor remaining indirect labor project requires total investment 128666 us 60 financed bank credit 40 contribution following results obtained financial economic evaluation npv 12 discount rate equal 168323 us irr 4104 ratio bc equal 135the economic evaluation consists measuring net contribution project national wellbeing way following indicators taken account employment generation demand raw materials valueadded services result environmental evaluation environmentalecological point view compliance environmental law polluting agents mitigation measures identified likewise environmental law classifies project within category 3 requires formulation mitigation measures environmental monitoring adequate control production process avoid irregularities order take corrective mitigation measures time to general objective project develop feasibility study production marketing coffee chañar fruit metropolitan axis cochabamba technical administrative commercial financial analysis response needs consumers market study carried determine demand supply product well marketing plan way study carried supply raw materials location location production plant defining production process infrastructure appropriate technology organizational structure must also developed define human resources required project financial economic feasibility determined different profitability indicators finally estimate possible environmental impacts units analysis families metropolitan axis cochabamba supply raw materials well location plant collect information different sources companies used mainly ine national institute statistics surveys interviews carried target population hand internet catalogues scientific articles quotes technology equipment consulted techniques analysis as sampling tabulation data determine demand supply product weighted averages location plant process flow diagram definition production process organization chart job evaluation organizational structure finally economic financial study project carried out study considers different elements determine profitability projects investments based evaluation criteria used evaluation criteria are irr npv bc tools used project results obtained as demand chañar coffee market acceptance main suppliers raw materials location chañar coffee production production process defined technology company organization chart functions them investment costs income finally degree percentage environmental impact
Columns: 151960 entries, 000 to μij this
dtypes: float64(151960)
memory usage: 1.3+ GB

Dentro de la arquitectura de despliegue, hay que cuidad la latencia(velocidad) y volumen

![image_1777069862282.png](./image_1777069862282.png "image_1777069862282.png")

In [0]:
# search test 5

query = "academic plan"

search_similar_documents(query, vectorizer_abs,X_abs,list_title_clear, list_title_clear_es)

Score: 0.1753
Documento (EN): ACADEMIC DEVELOPMENT PLAN FOR THE ELECTROMECHANICAL ENGINEERING CAREER 2019 – 2023
Documento (ES): PLAN DE DESARROLLO ACADÉMICO DE LA CARRERA DE INGENIERÍA ELECTROMECÁNICA 2019 – 2023
--------------------------------------------------

Score: 0.1378
Documento (EN): CURRICULAR TRANSFORMATION PROJECT FOR THE DEGREE COURSE IN INDUSTRIAL ENGINEERING OF THE FACULTY OF SCIENCES AND TECHNOLOGY OF THE UNIVERSIDAD MAYOR DE SAN SIMÓN
Documento (ES): PROYECTO DE TRANSFORMACIÓN CURRICULAR PARA LA CARRERA LICENCIATURA EN INGENIERÍA INDUSTRIAL DE LA FACULTAD DE  CIENCIAS Y TECNOLOGÍA DE LA UNIVERSIDAD MAYOR DE SAN SIMÓN
--------------------------------------------------

Score: 0.1271
Documento (EN): STRATEGIC DEVELOPMENT PLAN FOR THE SYSTEMS ENGINEERING COURSE OF THE FACULTY OF SCIENCES AND TECHNOLOGY OF THE UNIVERSIDAD MAYOR DE SAN SIMÓN 2019-2023
Documento (ES): PLAN ESTRATÉGICO DE DESARROLLO PARA LA CARRERA DE INGENIERÍA DE SISTEMAS DE LA FACULTAD DE CIENCIAS Y TECNOLOGÍA DE LA UNIVERSIDAD MAYOR DE SAN SIMÓN   2019-2023
--------------------------------------------------

Score: 0.1271
Documento (EN): STRATEGIC DEVELOPMENT PLAN FOR THE COURSE OF CIVIL ENGINEERING AT THE UNIVERSIDAD MAYOR DE SAN SIMÓN
Documento (ES): PLAN ESTRATÉGICO DE DESARROLLO PARA LA CARRERA DE INGENIERÍA CIVIL DE LA UNIVERSIDAD MAYOR DE SAN SIMÓN
--------------------------------------------------

Score: 0.1152
Documento (EN): PREPARATION OF A SAFETY, OCCUPATIONAL HEALTH AND WELL-BEING PLAN, UNDER THE REQUIREMENTS OF THE NB-OHSAS STANDARD 18001 VERSION 2008, FOR THE “AROCAGUA” INFOCAL CBBA FOUNDATION.
Documento (ES): ELABORACION DE UN PLAN DE SEGURIDAD, SALUD OCUPACIONAL Y BIENESTAR, BAJO LOS    REQUISITOS DE LA NORMA NB-OHSAS 18001 VERSION 2008, PARA LA FUNDACION INFOCAL CBBA ”AROCAGUA”.
--------------------------------------------------

array([1013,  967, 1000,  947,  957])

Asi como se puede usar el algoritmo para la busqueda, igual puede ser de ayuda para "Sistemas de recomendacion" por similutd de items

![image_1777070050894.png](./image_1777070050894.png "image_1777070050894.png")

In [0]:
# search test 6

query = "ypfb"

search_similar_documents(query, vectorizer_abs,X_abs,list_title_clear, list_title_clear_es)

Score: 0.1866
Documento (EN): DEVELOPMENT OF A STRATEGIC MARKETING PLAN FOR THE NEW SAE 10W30 API SN OIL LINE OF THE YPFB LUBRICANTS BRAND
Documento (ES): DESARROLLO DE UN PLAN ESTRATÉGICO DE MARKETING PARA LA NUEVA LÍNEA DE ACEITE SAE 10W30 API SN DE LA MARCA YPFB LUBRICANTES
--------------------------------------------------

Score: 0.1700
Documento (EN): INDUSTRIAL SAFETY AND HYGIENE PLAN FOR THE COMPANY “YPFB FLAMAGAS S.A.”
Documento (ES): PLAN DE SEGURIDAD E HIGIENE INDUSTRIAL PARA LA EMPRESA  “YPFB FLAMAGAS S.A.
--------------------------------------------------

Score: 0.0785
Documento (EN): FEASIBILITY STUDY TO IMPLEMENT A HOUSEHOLD GAS NETWORK INSTALLATION COMPANY IN COCHABAMBA
Documento (ES): ESTUDIO DE FACTIBILIDAD PARA IMPLANTAR UNA EMPRESA DE INSTALACIÓN DE REDES DE GAS DOMICILIARIO EN COCHABAMBA
--------------------------------------------------

Score: 0.0784
Documento (EN): EVALUATION AND DEVELOPMENT OF IMPROVEMENTS OF THE OPERATIONAL PROCESSES IN “YPFB LOGÍSTICA-PLANTA COCHABAMBA”
Documento (ES): EVALUACIÓN Y DESARROLLO DE MEJORAS DE LOS PROCESOS OPERACIONALES EN ”YPFB LOGÍSTICA-PLANTA COCHABAMBA”
--------------------------------------------------

Score: 0.0639
Documento (EN): PREFEASIBILITY STUDY FOR A DAP/NPK MINERAL FERTILIZER PRODUCTION PLANT IN BOLIVIA, FOR THE INDUSTRIALIZATION MANAGEMENT OF YPFB
Documento (ES): ESTUDIO DE PREFACTIBILIDAD PARA UNA PLANTA PRODUCTORA DE FERTILIZANTES MINERALES DAP/NPK EN BOLIVIA, PARA LA GERENCIA DE INDUSTRIALIZACIÓN DE YPFB
--------------------------------------------------

array([723, 814, 730, 370, 265])

In [0]:
# search test 7

query = "digital library"

search_similar_documents(query, vectorizer_abs,X_abs,list_title_clear, list_title_clear_es)

Score: 0.2219
Documento (EN): DEVELOPMENT OF A DIGITAL LIBRARY IN THE INDUSTRIAL ENGINEERING COURSE
Documento (ES): DESARROLLO DE UNA BIBLIOTECA DIGITAL EN LA CARRERA DE INGENIERÍA INDUSTRIAL
--------------------------------------------------

Score: 0.0909
Documento (EN): STRATEGIC MARKETING PLAN FOR THE DIGITAL MARKETING COMPANY “SOCIAL BRAND” FOR SMEs IN THE CITY OF COCHABAMBA.”
Documento (ES): PLAN ESTRATÉGICO DE MARKETING PARA LA EMPRESA DE MARKETING DIGITAL “SOCIAL BRAND” PARA PYMES EN LA CIUDAD DE COCHABAMBA”.
--------------------------------------------------

Score: 0.0633
Documento (EN): BUSINESS PLAN FOR THE EXPANSION OF REPAIR AND MAINTENANCE SERVICES OF ELECTRONIC AND DIGITAL HOME EQUIPMENT FOR THE COMPANY SISTEC (ELECTRICAL TECHNICAL SYSTEMS).
Documento (ES): PLAN DE NEGOCIOS PARA LA AMPLIACION DE SERVICIOS DE REPARACION Y           MANTENIMIENTO DE EQUIPOS ELECTRONICOS Y DIGITALES DEL HOGAR PARA LA EMPRESA SISTEC (SISTEMAS TÉCNICOS ELÉCTRICOS).
--------------------------------------------------

Score: 0.0432
Documento (EN): IMPLEMENTATION OF VERIFICATION PROCEDURES TO INSTRUMENTS WITHIN THE SECTOR MANAGEMENT OF INSTRUMENTATION AND PROCESS CONTROL IN THE GUALBERTO VILLARROEL REFINERY – Y.P.F.B. REFINING S.A.
Documento (ES): IMPLEMENTACIÓN DE PROCEDIMIENTOS DE VERIFICACIÓN A INSTRUMENTOS DENTRO LA GERENCIA SECTORIAL DE INSTRUMENTACIÓN Y CONTROL DE PROCESOS EN LA REFINERÍA GUALBERTO VILLARROEL – Y.P.F.B. REFINACIÓN S.A.
--------------------------------------------------

Score: 0.0232
Documento (EN): OPTIMIZATION OF THE HANDLING OF MACHINE TOOLS THROUGH THE STUDY OF METHODS AND REENGINEERING FOR THE “ACTROS GRINDING MACHINE”.
Documento (ES): OPTIMIZACIÓN DEL MANEJO DE MÁQUINAS HERRAMIENTAS MEDIANTE EL ESTUDIO DE MÉTODOS Y REINGENIERÍA PARA LA “RECTIFICADORA ACTROS”.
--------------------------------------------------

array([ 674, 1118,  484,  488,  521])

Por nuestra experiencia podemos determinar si los output tienen logica

![image_1777069719076.png](./image_1777069719076.png "image_1777069719076.png")